### ISSUE TITLE
unable to get status

### ISSUE THREAD

**Issue by MrTimonM** [zamzasalim/sonic-arcade#3]
⠙ 
[acc][1] Address      : 0xC3195xxxxxxxxxx510D2779D4
[acc][1] Balance      : 10.0 S
[acc][1] Point        : Total - | Today -
[acc][1] Status       : Error : 500 - Internal Server Error, Retry again after 10 Seconds
[acc][1] Delay        : Delaying for 0 Hours 0 Minutes 2 Seconds

**Comment by zamzasalim** [comment]
![xxx](https://github.com/user-attachments/assets/b8017ac1-54fa-4a64-8a5a-bd3731a6ebbe)
Claim faucet $TOKEN
